# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazar.Unit'),
        ),
    ]
