# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
