# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_auto_20180113_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
