# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 19:50
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180103_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
